config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'signup', to: 'users#new' #signupという名前でアクセスできるように
  get 'login', to:  'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'  
  
  get 'followings/:id', to: 'users#followings', as: 'followings'
  get 'followers/:id', to: 'users#followers', as: 'followers'
  
  get 'users_all', to: 'users#users_all', as: 'users_all'

  get 'inbox', to: 'users#inbox'
  get 'sendmail', to: 'users#sendmail'
  
  get 'words', to: 'words#show'
  
  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  
  resources :mailboxes, only: [:create]

  # for Twitter login
  get "/auth/:provider/callback", to: "sessions#omniauth_callbacks"
  # fot Rakuten Recipe
  get "new", to: "words#new"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    on: :create
  

  has_secure_password
  
  # 「dependent: :destroy」userが削除された場合に一緒に削除する
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  
  
  # ---- ダイレクトメール ---------------
  has_many :mailboxes
  
  # 受信メール一覧を取得
  def feed_mails
     Mailbox.where(recipient_id: [self.id])
  end
  # -------------------------------------
    
    # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  #自分とフォローしているユーザーのつぶやきを取得する
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        name:     auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        # twitterではemailを取得できないので、適当に一意のemailを生成
        email:   SecureRandom.urlsafe_base64 + "@example.com",
        # twitterではpasswordが取得できないので、適当にパスワードを生成
        password_digest:  SecureRandom.urlsafe_base64
      )
    end

    user
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :correct_user, only:[:edit, :update]
  before_action :logged_in_ok?, only:[:show, :followers, :followings, :users_all,:sendmail, :inbox]
  
  def show
      @user= User.find(params[:id])
      @microposts = @user.microposts
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    #binding.pry
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      #sessionを発行
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id]);
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      render 'edit'
    end  
  end
  
  #フォロー一覧
  def followings
      @user = User.find(params[:id])
      @follwing_users = @user.following_users
  end
  
  #フォロワー一覧
  def followers
      @user = User.find(params[:id])
      @follower_users = @user.follower_users
  end
  
  #ユーザー一覧
  def users_all
    @users=User.all.page params[:page]
  end
  
  # --受信メールボックス 
  def inbox 
    @feed_mails = current_user.feed_mails.includes(:user).order(created_at: :desc).page params[:page]
    #既読フラグ、1なら既読、それ以外は未読
    @feed_mails.each do |msg|
        msg.read = 1
        msg.save!
    end     
  end
  
  # --ショートメール送信フォーム --
  def sendmail
    if logged_in?
     @recipient_id = params[:recipient_id]
     @mailbox = current_user.mailboxes.build
    end
  end
  
  
  #ログインしているかどうか確認し、ログインしていない場合はログイン画面に戻す
  def logged_in_ok?
    unless logged_in?
      flash[:warning] = "このページを閲覧するにはログインが必要です"
      store_location
      redirect_to login_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:profile,:address)
  end
  
  #ログインしているユーザーが本人なのかどうかを確認する
  #ユーザー情報の編集を本人意外行えないようにするための処置
  def correct_user
    #correct_user?関数はapplication_controllerに実装
    correct_user?(params[:id])
  end
  

  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  #未読メッセージを表示する
  def mailcount_for(user)
    @unread = Mailbox.where(read: 0, recipient_id: user).count
    @unread if @unread >= 1
  end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_mail_button.html.erb
<% if current_user != @user %>
  <%= form_tag(sendmail_path, method: "get") do %>
    <%= hidden_field_tag :recipient_id, @user.id %>
    <%= submit_tag("ショートメールを送る", class: "btn btn-primary") %>
  <% end %>
<% end %>

app/views/users/_mail_form.html.erb
<% if current_user != @user %>
  <%= form_tag(sendmail_path, method: "get") do %>
    <%= hidden_field_tag :recipient_id, @user.id %>
    <%= submit_tag("ショートメールを送る", class: "btn btn-primary") %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "unfollow", class: "btn" %>
<% end %>

app/views/users/_user_profile.html.erb
<div class="userprofile text-center">
    
  <section class="user_info">
    <%= gravatar_for @user %>
    <div class="content">
      <p class="text-left"><strong><%= @user.name %></strong></p>
      <p class="text-left small">
        <i class="glyphicon glyphicon-envelope"></i> <%= @user.email %><br>
        <%= @user.address %>
      </p>
    </div>
  </section>
      
  <div class="info text-left">
    <p>
    <%= @user.profile %>
    <p>
  </div>
    
  <div class="col-sm-6">
    <a href="<%= followings_path(@user) %>">
    <p><font size="20px"><%= @user.following_users.count %></font></p>
    </a>
    <p><small>フォロー</small></p>
  </div>
  
  <div class="col-sm-6">
    <a href="<%= followers_path(@user) %>">
    <p><font size="20px"><%= @user.follower_users.count %></font></p>
    </a>
    <p><small>フォロワー</small></p>
  </div>
      
  <%= render 'follow_form' if logged_in? %>
  
  <%= render 'mail_button' if logged_in? %>  
</div><!-- .userprofile text-center -->

app/views/users/edit.html.erb
<h1>edit your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
      
      <div class="form-group">
      <%= f.label :name, 'なまえ' %>
      <%= f.text_field :name, placeholder: "なまえ", class: "form-control" %>
      </div>
      
      <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
      </div>
      
      <div class="form-group">
      <%= f.label :address, '出身地' %>
      <%= f.text_field :address, placeholder: "出身地", class: "form-control" %>
      </div>
      
      <div class="form-group">
      <%= f.label :profile, '自己紹介' %>
      <%= f.text_area :profile, placeholder: "自己紹介", class: "form-control" %>
      </div>

      <%= f.submit "Edit my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">

  <aside class="col-md-4">
   <%= render "user_profile" %> 
  </aside>
  
  
  <div class="col-md-8">
    <% if @follower_users.any? %>
      <h3>フォロワー (<%= @follower_users.count %>)</h3>
      <ol class="follower">
        <% @follower_users.each do |follower_user| %>     
        <li id="follower-<%= follower_user.id %>">
          <%= link_to gravatar_for(follower_user, size: 50), follower_user %>
          <span class="user"><%= link_to follower_user.name, follower_user %><br></span>
          <span class="profile"><%= follower_user.profile %></span>
        </li>
      <% end %> 
      </ol>
    <% end %>
  </div>
  
</div>

app/views/users/followings.html.erb
<div class="row">

  <aside class="col-md-4"> 
   <%= render "user_profile" %>    
  </aside>
  
  
  <div class="col-md-8">
    <% if @follwing_users.any? %>
      <h3>フォロー中 (<%= @follwing_users.count %>)</h3>
      <ol class="follower">
        <% @follwing_users.each do |follwing_user| %>  

        <li id="follwing-<%= follwing_user.id %>">
          <%= link_to gravatar_for(follwing_user, size: 50), follwing_user %>
          <span class="user"><%= link_to follwing_user.name, follwing_user %><br></span>
          <span class="profile"><%= follwing_user.profile %></span>
        </li>
        <% end %> 
      </ol>      
    <% end %>
  </div>
  
</div>

app/views/users/inbox.html.erb
<div class="row">
  <div class="col-md-10 content">
  <h3>受信メッセージ一覧</h3>
  <hr>
  
    <% if @feed_mails.any? %>
    　<%= paginate @feed_mails %>
    　
      <% @feed_mails.each do |msg| %>
        <div class="panel panel-default">
        
          <div class="panel-heading">
            <p>FROM: <%= link_to msg.user.name, msg.user %> </p>
            <p>日時:  <%= msg.created_at %></p>
            
          </div>
        
          <div class="panel-body">
            <p><%= msg.message %></p>      
            <div class="col-md-2 content">
              <%= form_tag(sendmail_path, method: "get") do %>
                <%= hidden_field_tag :recipient_id, msg.user_id %>
                <%= submit_tag("返信する", class: "btn btn-primary") %>
              <% end %> 
            </div>         
          </div><!-- /.panel-body -->
          
        </div><!-- /.panel panel=default -->
      <% end %> 
     
    <% else %>
    <h2>受信メッセージはありません</h2>
    <% end %>
  </div><!-- /.col-md-10 content -->
</div><!-- .row -->

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
      
      <div class="form-group">
      <%= f.label :name, 'なまえ' %>
      <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password_confirmation, "パスワード（確認用）" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/sendmail.html.erb
<div class="row">
<h3><i class="glyphicon glyphicon-envelope"></i>
 ショートメッセージ作成フォーム</h3>
<hr>


  <div class="col-md-6">
  <p>200文字以内でショートメールを作成してください</p>
    <%= form_for(@mailbox) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= hidden_field_tag :recipient_id, @recipient_id %>
      <%= f.hidden_field :recipient_id, :value => @recipient_id %>
      <div class="field">
        <%= f.text_area :message, placeholder: "200文字以内でメッセージを入力してください", :size => "60x10" %>
      </div>
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div>
  
</div>

app/views/users/show.html.erb
<div class="row">

  <aside class="col-md-4"> 
    <%= render "user_profile" %>       
  </aside>
  
  
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
  
</div>

app/views/users/users_all.html.erb
<div class="row">

  <aside class="col-md-4"> 
    
  </aside>
  
  
  <div class="col-md-8">
    <h3>ユーザー一覧</h3>
    <%= paginate @users %>
    
    <div class="userlist">
      <ol class="follower">
        <% @users.each do |user| %>     
        <li id="user-<%= user.id %>">
          <%= link_to gravatar_for(user, size: 50), user %>
          <span class="user"><%= link_to user.name, user %><br></span>
          <span class="profile"><%= user.profile %></span>
        </li>
        <% end %> 
      </ol>
    </div>

  </div>
  
</div>