config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'signup', to: 'users#new' #signupという名前でアクセスできるように
  get 'login', to:  'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'  
  
  get 'followings/:id', to: 'users#followings', as: 'followings'
  get 'followers/:id', to: 'users#followers', as: 'followers'
  
  get 'users_all', to: 'users#users_all', as: 'users_all'

  get 'inbox', to: 'users#inbox'
  get 'sendmail', to: 'users#sendmail'
  
  get 'words', to: 'words#show'
  
  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  
  resources :mailboxes, only: [:create]

  # for Twitter login
  get "/auth/:provider/callback", to: "sessions#omniauth_callbacks"
  # fot Rakuten Recipe
  get "new", to: "words#new"
  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "cutie Note", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      
        <li><%= link_to sanitize('<i class="glyphicon glyphicon-home"></i> '), root_path %></li>
        
        <% if logged_in? %>
        
        <li>
        <%= link_to inbox_path do %>                                                                                              
          <i class="glyphicon glyphicon-envelope"></i> 
          <span style="color: red;"><%= raw mailcount_for(current_user) %></span>
        <% end %> 
        </li>
        
        <li>
        <%= link_to words_path do %>                                                                                              
          <i class="glyphicon glyphicon-book"></i> 
        <% end %> 
        </li>
               
        
        <li><%= link_to sanitize('<i class="glyphicon glyphicon-user"></i> '), users_all_path %></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %> 
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
      <%= yield %>
    </div> 
  </body>
</html>